import os

DATA_DIR = os.getenv("BARDI_B_DATA_DIR")

# The directory in which to store all models.
MODELS_DIR = os.path.join(DATA_DIR, "models/")

# The root directory for all data generated by the app...
# TODO: Use a database :P
SHAKESPEARE_DATA_DIR = os.path.join(DATA_DIR, "shakespeare/")

VILLAINS = [
    {"play": "hamlet", "character": "claudius"},
    {"play": "king-lear", "character": "regan"},
    {"play": "king-lear", "character": "goneral"},
    {"play": "king-lear", "character": "edmund"},
    {"play": "othello", "character": "iago"},
    {"play": "much-ado-about-nothing", "character": "don-john"},
    {"play": "macbeth", "character": "lady-macbeth"},
    {"play": "richard-iii", "character": "richard-iii"},
    {"play": "julius-caesar", "character": "cassius"},
    {"play": "romeo-and-juliet", "character": "tybalt"},
]
JESTERS = [
    {"character": "a-fool", "play": "timon-of-athens"},
    {"character": "autolycus", "play": "the-winters-tale"},
    {"character": "citizen", "play": "julius-caesar"},
    {"character": "cloten", "play": "cymbeline"},
    {"character": "clown", "play": "othello"},
    {"character": "clown", "play": "titus-andronicus"},
    {"character": "costard", "play": "loves-labours-lost"},
    {"character": "dogberry", "play": "much-ado-about-nothing"},
    {"character": "dromio of ephesus", "play": "the-comedy-of-errors"},
    {"character": "dromio of syracuse", "play": "the-comedy-of-errors"},
    {"character": "falstaff", "play": "henry-iv-part-1"},
    {"character": "falstaff", "play": "henry-iv-part-2"},
    {"character": "feste", "play": "twelfth-night"},
    {"character": "grumio", "play": "the-taming-of-the-shrew"},
    {"character": "launce", "play": "two-gentlemen-of-verona"},
    {"character": "launcelot gobbo", "play": "the-merchant-of-venice"},
    {"character": "lavache", "play": "alls-well-that-ends-well"},
    {"character": "nick bottom", "play": "a-midsummer-nights-dream"},
    {"character": "pompey", "play": "measure-for-measure"},
    {"character": "puck", "play": "a-midsummer-nights-dream"},
    {"character": "speed", "play": "two-gentlemen-of-verona"},
    {"character": "the-fool", "play": "king-lear"},
    {"character": "the-gravediggers", "play": "hamlet"},
    {"character": "the-porter", "play": "macbeth"},
    {"character": "thersites", "play": "troilus-and-cressida"},
    {"character": "touchstone", "play": "as-you-like-it"},
    {"character": "trinculo", "play": "the-tempest"},
    {"character": "yorick", "play": "hamlet"},
]
DREAMERS = [
    {"character": "ophelia", "play": "hamlet"},
    {"character": "hamlet", "play": "hamlet"},
    {"character": "julia", "play": "romeo-and-juliet"},
    {"character": "romeo", "play": "romeo-and-juliet"},
]
